swagger: '2.0'
info:
  version: "1.0.0"
  title: "Your App Name"
  description: "API documentation for Your App Name"
basePath: "/"
schemes:
  - "http"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Enter 'Bearer' [space] and then your token in the text input below.\n\nExample: \"Bearer abcde12345\""
paths:
  /signup:
    post:
      tags:
        - "User"
      summary: "User Signup"
      description: "User Signup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be added"
          required: true
          schema:
            type: "object"
            required:
              - "username"
              - "password"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "User successfully signed up"
        400:
          description: "Invalid input"
  /signin:
    post:
      tags:
        - "User"
      summary: "User Signin"
      description: "User Signin"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User credentials for signin"
          required: true
          schema:
            type: "object"
            required:
              - "username"
              - "password"
            properties:
              username:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "User successfully signed in"
        401:
          description: "Invalid credentials"
  /chatbot:
    post:
      tags:
        - "Chatbot"
      summary: "Chat with the bot"
      description: "Chat with the bot"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Message to send to the chatbot"
          required: true
          schema:
            type: "object"
            required:
              - "message"
            properties:
              message:
                type: "string"
      responses:
        200:
          description: "Chatbot response"
        401:
          description: "Unauthorized"
      security:
        - Bearer: []